# .github/actions/build-test.yml
name: Build and Test
on: 
  push:
    branches-ignore:
    - 'gh-pages'

jobs:
  build:
    name: Build and Test
    # Choose the operating system to run the build on
    runs-on: ubuntu-latest
    # Run the build
    steps:
    # Checkout a copy of the repository
    - uses: actions/checkout@v2
    # Create a build folder
    - run: mkdir Worksheet7/build
    # Build the repo
    - name: Build
      working-directory: Worksheet7/build
      run: |
        cmake ..
        make
    # Run the tests
    - name: Test
      run: make test
      working-directory: Worksheet7/build
